sudo: false
language: node_js
node_js:
- '8.5'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
after_success:
- bash ./scripts/deploy.sh
env:
  global:
  - GH_USER: petermuessig
  - GH_REPO: my-ui5-app
  - secure: TuhgyXUvMeT/6OiD4iKB2pAM1nc9yQ9X5FvYkgKm2vFrpGxTNa0XzfZamRDdN/q1qNuV6uykggH6oXe4KjbeWMVVhH1rqhPZfqaPTcziESOC2POlPG3PNvinbWdhk6e1wQ2uhk0IdGtAjKuJXvHmhipjqDa5nKEalTWkAolMYWWyjjub4ybu3b4aIFUmjutYJO71pLgCZ1QNt+OmVHh+PMl/MqolMKKJ0oup6gr3Z19HcFKGMtt/Ch5FMQLN6S12xrieyGLmzTAKUMcqlUw5V9GuOQ/rxKsfGPujnY0zNeffq+fsLeHSYHapvuv/LHDSdPTQYpvZMJ6gAaW+haLreSN4V04Z4Cf4+vPJL6pOWjPGDT/Qk3M2BoxkmhWAhFrt0VZYK2q2jC4jaPGSQE6lNZxtUy1mtilfhP/uMIQIYNZbRXkl6luEah9RJJHOQtiNUV1TXC/s+3u8nAYLJWIegexqbS4cqo/iOiK0zxlfKkDuKSSXsfFC4JCvjLJ22n40v+xjxexXIOtK4sfyMWQNpvGWNsP28mEIXc8kbqPA/pYlBBF27BB+GYk3TB04nE2/xhuJ/mcJS7X+Sd+fWbj1JBGMbhH4ui/GVTcWOylGlAFR7sTBFXpYrBUcrUN5+Yhi63mGvMjeQ0GDG3RGzt3lD/8q7eYK7xj3VjvYA173/G8=
