sudo: false
language: node_js
node_js:
- '8.5'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
after_success:
- bash ./scripts/deploy.sh
env:
  global:
  - GH_USER: petermuessig
  - GH_REPO: my-ui5-app
  - secure: X5tS1fV3wzcY1NPLnAJsSNIvqBYUN37bXlw5hhzksJHDYQkLrfbTSaCdJvknQrozKCHKKO2QaC9T64b/3rmTwhOn4Xd2wz/w0nwsabbxDs7A38iokBRk2eQDZbHxcDpQdOLTT2Q2KPMr0GpbgeiPqsIwISt3csxfm5Drmg/Kaa912LGd7CI3x7Av0T9Q0VrwGNNnsKMgL/MzjH/OR8xkMvLXcniM6+jXIcYBpl/lhSN6uSDqrs8mL2FDl5QdEaG1Mc/ikqklIsHlPQW5XUZtFHHXxD9REDU6NmoKMSvpIZnmr9POCaPvjjIqMuxz1/zyVYtHuiUqrBZ3WZsxEJJ4VllL9BrxKwNsS8OVffKaOMu30UiqGqYrmY03pMjjw8lIeseRz0ZrIzwN5u+T6A/v0H/x967Q2XPOBlLlng+qWslZ1nf78rEkbfFJUbpRulG6JObQeBT0AUHup4R2UK9JJWsWeA/BMKzVTmVPujLID85zDkbN8tahphAynETV+VDtjyh9B9lv/jX3lJzVScgHgS9mmjRF9D18QQQHo32M+5eb38MTygp2vVTnwxxNIc69Tfdx85UfnYtWn+SVxtNA0h1shkR0aAl/bK7mo5I92H2VfMIvEGKyOOz9Ea5whfqo1PG/UpZta3BXqdczSx9RxCOI76LN+oh5OO6wRkTK49o=
